# translate_batch_B.py 完整内容
import json, os
T = {
    # ===== 202_8 =====
    'script:202_8:diag0': {'meta_zh': '麻耶', 'zh_pages': ['\n<SURNAME/>指南针也乱了…<pause:30/>\n<SURNAME/>方向感都怪怪的，\n<SURNAME/>要是没有灯光，肯定迷路。\n']},
    'script:202_8:diag1': {'meta_zh': '麻耶', 'zh_pages': ['\n<SURNAME/>找不到出口…吗。<pause:30/>\n<SURNAME/>找不到…找不到…\n']},
    'script:202_8:diag2': {'meta_zh': '麻耶', 'zh_pages': ['\n<SURNAME/>镜…镜…<pause:30/>\n<SURNAME/>"找不到出口"传闻，\n<SURNAME/>跟"镜子"传闻…啊。\n']},
    'script:202_8:diag3': {'meta_zh': '荣吉', 'zh_pages': ['\n<SURNAME/>有门倒是有门，可能是出口才怪…<pause:30/>\n<SURNAME/>毕竟传闻就是"找不到"嘛…\n']},
    'script:202_8:diag4': {'meta_zh': '荣吉', 'zh_pages': ['\n<SURNAME/>呜哦哦哦!?\n<SURNAME/>又是这里!?\n<SURNAME/>哪里都没出口嘛!\n']},
    'script:202_8:diag5': {'meta_zh': '荣吉', 'zh_pages': ['\n<SURNAME/>传闻说带着镜子的家伙，只有一个人逃出去了…<pause:30/>\n<SURNAME/>可没出口的话，怎么搞都没用啊…<pause:30/>\n<SURNAME/>这下，真的完蛋了…\n']},
    'script:202_8:diag6': {'meta_zh': '丽莎', 'zh_pages': ['\n<SURNAME/>哎呀!?(アイヤー)\n<SURNAME/>这东西要喝下去~?\n<SURNAME/>烦哪!(ファーンナ)不要不要不要!!\n']},
    'script:202_8:diag7': {'meta_zh': '丽莎', 'zh_pages': ['\n<SURNAME/>好伤呀…(木ゥシヨンア)\n<SURNAME/><c13/>~人家口渴啦~\n<SURNAME/>这种水，才不想喝~\n']},
    'script:202_8:diag8': {'meta_zh': '丽莎', 'zh_pages': ['\n<SURNAME/>咕…<pause:30/>\n<SURNAME/>不行不行!\n<SURNAME/>喝了这玩意儿会死人的!\n']},
    'script:202_8:diag9': {'meta_zh': '雪乃', 'zh_pages': ['\n<SURNAME/>有水渗出来…<pause:30/>\n<SURNAME/>总算饮用水有着落了。\n']},
    'script:202_8:diag10': {'meta_zh': '雪乃', 'zh_pages': ['\n<SURNAME/>就说大小姐麻烦嘛…<pause:30/>\n<SURNAME/>没事啦。\n<SURNAME/>虽然有虫子，但是能喝的水。\n']},
    'script:202_8:diag11': {'meta_zh': '雪乃', 'zh_pages': ['\n<SURNAME/>看来咱们把那个康夫小看了…<pause:30/>\n<SURNAME/>岩壁这么厚，\n<SURNAME/>用 Persona 也凿不开啊…\n']},
    'script:202_8:diag12': {'meta_zh': '麻耶', 'zh_pages': ['\n<SURNAME/><c13/>，\n<SURNAME/>那边不是刚才进来的门吗?\n<SURNAME/>从反方向那扇出去吧。\n']},
    'script:202_8:diag13': {'meta_zh': '麻耶', 'zh_pages': ['\n<SURNAME/><c13/>，\n<SURNAME/>那边不是刚才进来的门吗?\n<SURNAME/>从反方向那扇出去吧。\n']},

    # ===== 203_8 =====
    'script:203_8:diag0': {'meta_zh': '丽莎', 'zh_pages': ['\n<SURNAME/>好伤呀…(木ゥシヨンア)<pause:30/>\n<SURNAME/>累死啦~\n<SURNAME/>出口根本不存在嘛!?\n']},
    'script:203_8:diag1': {'meta_zh': '麻耶', 'zh_pages': ['\n<SURNAME/>那个，丽莎。\n<SURNAME/>你…带镜子了吗?\n']},
    'script:203_8:diag2': {'meta_zh': '麻耶', 'zh_pages': ['\n<SURNAME/>刚才听荣吉说，\n<SURNAME/>那个一个人逃出去的人，\n<SURNAME/>传闻就是用了"镜子"的吧?\n']},
    'script:203_8:diag3': {'meta_zh': '丽莎', 'zh_pages': ['\n<SURNAME/>唔係(ンハイ)\n<SURNAME/>嗯…现在没带…<pause:30/>\n<SURNAME/>我平常都放在包里嘛。\n']},
    'script:203_8:diag4': {'meta_zh': '荣吉', 'zh_pages': ['\n<SURNAME/>哦哦，不~<pause:30/>\n<SURNAME/>三位美女在场，居然连一面镜子都掏不出~\n<SURNAME/>啊…多么 beauti 木ゥ…\n']},
    'script:203_8:diag5': {'meta_zh': '丽莎', 'zh_pages': ['\n<SURNAME/>说你呢，有就快拿出来呀!!\n<SURNAME/>盯着这种臭脸，\n<SURNAME/>什么都改变不了好不好!!\n']},
    'script:203_8:diag6': {'meta_zh': '荣吉<SURNAME/>丽莎', 'zh_pages': ['\n<SURNAME/>啊————————————!?\n']},
    'script:203_8:diag7': {'meta_zh': '丽莎', 'zh_pages': ['\n<SURNAME/>哎…<pause:15/>呀~(アイ…ヤ~)<pause:30/>\n<SURNAME/>这下怎么办!?\n<SURNAME/>负责啦!<SURNAME/>笨蛋!!\n']},
    'script:203_8:diag8': {'meta_zh': '荣吉', 'zh_pages': ['\n<SURNAME/>是你害的吧!?\n<SURNAME/>赔偿!赔偿!!\n<SURNAME/>一百万!一百万!!\n']},
    'script:203_8:diag9': {'meta_zh': '雪乃', 'zh_pages': ['\n<SURNAME/>你俩适可而止!!\n<SURNAME/>就因为你们，\n<SURNAME/>最后的线索也没啦，知道吗!?\n']},
    'script:203_8:diag10': {'meta_zh': '荣吉<SURNAME/>丽莎', 'zh_pages': ['\n<SURNAME/>啊~完蛋啦~\n']},
    'script:203_8:diag11': {'meta_zh': '麻耶', 'zh_pages': ['\n<SURNAME/>Let\'s Positive Thinking!!\n<SURNAME/>说"完了"的是你自己，那才真完了。<pause:30/>\n<SURNAME/>想!<SURNAME/>肯定有办法的!\n']},
    'script:203_8:diag12': {'meta_zh': '雪乃', 'zh_pages': ['\n<SURNAME/>麻耶姐。大家都累了。\n<SURNAME/>为了清醒一下脑子，先休息吧。\n<SURNAME/>轮流守夜就好。\n']},
    'script:203_8:diag13': {'meta_zh': '麻耶', 'zh_pages': ['\n<SURNAME/><c13/>…<pause:30/>\n<SURNAME/>有点早，但要换班吗?\n']},
    'script:203_8:diag14': {'meta_zh': '麻耶', 'zh_pages': ['\n<SURNAME/>有点睡不着…<pause:30/>\n<SURNAME/>坐你旁边，可以吗?\n']},
    'script:203_8:diag15': {'meta_zh': '麻耶', 'zh_pages': ['\n<SURNAME/>说真的…<pause:30/>\n<SURNAME/>我们…能从这里出去吗?\n']},
    'script:203_8:diag16': {'meta_zh': '麻耶', 'zh_pages': ['\n<SURNAME/>啊，抱歉!\n<SURNAME/>Positive Thinking!\n']},
    'script:203_8:diag17': {'meta_zh': '麻耶', 'zh_pages': ['\n<SURNAME/>发牢骚的话，会被兔子小姐笑话哦?\n<SURNAME/>啊，蹦蹦跳跳!\n']},
    'script:203_8:diag18': {'meta_zh': '<c13/>', 'zh_pages': ['\n<SURNAME/>………\n']},
    'script:203_8:diag19': {'meta_zh': '麻耶', 'zh_pages': ['\n<SURNAME/>第一次看你笑呢?\n<SURNAME/>笑得真不错♥\n']},
    'script:203_8:diag20': {'meta_zh': '<c13/>', 'zh_pages': ['\n<SURNAME/>………\n']},
    'script:203_8:diag21': {'meta_zh': '麻耶', 'zh_pages': ['\n<SURNAME/>这小家伙是我的护身符…<pause:30/>\n<SURNAME/>难过或为难的时候，就找它商量。\n<SURNAME/>就像…现在这样…\n']},
    'script:203_8:diag22': {'meta_zh': '麻耶', 'zh_pages': ['\n<SURNAME/>说真的，搞成大事件了…<pause:30/>\n<SURNAME/>传闻变成现实，又被真正的恶魔袭击…\n']},
    'script:203_8:diag23': {'meta_zh': '麻耶', 'zh_pages': ['\n<SURNAME/>不过，也有好事呢。\n<SURNAME/>能跟<c13/>还有大家相识…\n']},
    'script:203_8:diag24': {'meta_zh': '麻耶', 'zh_pages': ['\n<SURNAME/>跟大家在一起，真的很快乐。\n<SURNAME/>就像…回到了小时候…\n']},
    'script:203_8:diag25': {'meta_zh': '麻耶', 'zh_pages': ['\n<SURNAME/>我啊，怎么都觉得 Joker，\n<SURNAME/>不像是真正的坏人。<pause:30/>\n<SURNAME/>就像…做噩梦哭泣的孩子…\n']},
    'script:203_8:diag26': {'meta_zh': '麻耶', 'zh_pages': ['\n<SURNAME/>你们也是，整天打架逞强，\n<SURNAME/>其实都是温柔的孩子，Persona 告诉了我。<pause:30/>\n<SURNAME/>同样的感觉…\n']},
    'script:203_8:diag27': {'meta_zh': '麻耶', 'zh_pages': ['\n<SURNAME/>这是<c13/>的护身符啊…<pause:30/>\n<SURNAME/>上面用英文刻着…<pause:30/>\n<SURNAME/>"真正重要的东西，眼睛是看不见的"…\n']},
    'script:203_8:diag28': {'meta_zh': '麻耶', 'zh_pages': ['\n<SURNAME/>是啊…<pause:30/>\n<SURNAME/>我有时候会觉得，眼前这现实，\n<SURNAME/>说不定全是一场梦。\n']},
    'script:203_8:diag29': {'meta_zh': '麻耶', 'zh_pages': ['\n<SURNAME/>很久以前忘了什么重要的东西，\n<SURNAME/>就这样做着醒不来的梦…<pause:30/>\n<SURNAME/>或许…Joker 也是…\n']},
    'script:203_8:diag30': {'meta_zh': '<c13/>', 'zh_pages': ['\n<SURNAME/>………\n']},
    'script:203_8:diag31': {'meta_zh': '麻耶', 'zh_pages': ['\n<SURNAME/>啊，对不起。\n<SURNAME/>聊太久了。\n<SURNAME/>来，守夜交给我，你去睡吧。\n']},
    'script:203_8:diag32': {'meta_zh': '麻耶', 'zh_pages': ['\n<SURNAME/>晚安，<c13/>…<pause:30/>\n<SURNAME/>做个…好梦吧。\n']},

    # ===== 204_8 =====
    'script:204_8:diag0': {'meta_zh': '少年', 'zh_pages': ['\n<SURNAME/>呐，<c13/>…<pause:30/>\n<SURNAME/>我们俩，长得真有那么像吗?']},
    'script:204_8:diag1': {'meta_zh': '少年', 'zh_pages': ['\n<SURNAME/>是啊…<pause:30/>\n<SURNAME/>我，一点都不讨厌。']},
    'script:204_8:diag2': {'meta_zh': '少年', 'zh_pages': ['\n<SURNAME/>对了，']},
    'script:204_8:diag3': {'meta_zh': '少年', 'zh_pages': ['\n<SURNAME/>这个，是爸爸送我的宝物…<pause:30/>\n<SURNAME/>送给<c13/>。']},
    'script:204_8:diag4': {'meta_zh': '少年', 'zh_pages': ['\n<SURNAME/>没关系。\n<SURNAME/>因为我就是你，你就是我嘛。\n<SURNAME/>跟我自己拿着没两样!']},
    'script:204_8:diag5': {'meta_zh': '少年', 'zh_pages': ['\n<SURNAME/>这是…<pause:30/>\n<SURNAME/>你爸爸送你的宝物对吧?\n<SURNAME/>不行啦…']},
    'script:204_8:diag6': {'meta_zh': '<c13/>', 'zh_pages': ['\n<SURNAME/>………']},
    'script:204_8:diag7': {'meta_zh': '少年', 'zh_pages': ['\n<SURNAME/>嗯，明白了。\n<SURNAME/>我会当宝贝!']},
    'script:204_8:diag8': {'meta_zh': '少年', 'zh_pages': [
        '\n<SURNAME/>啊哈哈哈!\n<SURNAME/>不知怎的好开心啊!',
        '<c1d:11/>少年<c1d:1/>\n<SURNAME/>我们俩，无论发生什么事，\n<SURNAME/>都要遵守刚才的约定!\n<SURNAME/>永远!<SURNAME/>永远!\n',
    ]},
    'script:204_8:diag9': {'meta_zh': '醉酒青年', 'zh_pages': ['\n<SURNAME/>再见啦，老板。\n<SURNAME/>我还会来的。\n<SURNAME/>嗯，说定了。\n']},
    'script:204_8:diag10': {'meta_zh': '醉酒青年', 'zh_pages': ['\n<SURNAME/>嗯~?<SURNAME/>不行啊。\n<SURNAME/>小孩子玩到这么晚。<pause:10/>\n<SURNAME/>会长不成正经大人哦?']},
    'script:204_8:diag11': {'meta_zh': '醉酒青年', 'zh_pages': ['\n<SURNAME/>好，没醉。<pause:10/>\n<SURNAME/>抓住梦想的男人的脸，<pause:5/>薰君。']},
    'script:204_8:diag12': {'meta_zh': '醉酒青年', 'zh_pages': ['\n<SURNAME/>那么，哥哥也要回家啦，<pause:10/>\n<SURNAME/>你们也快回家快回家!']},
    'script:204_8:diag13': {'meta_zh': '醉酒青年', 'zh_pages': ['\n<SURNAME/>不然就抓起来哦?']},
    'script:204_8:diag14': {'meta_zh': '少年', 'zh_pages': ['\n<SURNAME/>呐，<c13/>，你知道吗?<pause:5/>\n<SURNAME/>大人们，是为了忘掉梦想才喝酒的。\n<SURNAME/>我才不要…变成那种大人…\n']},

    # ===== 206_8 =====
    'script:206_8:diag0': {'meta_zh': '麻耶', 'zh_pages': ['\n<SURNAME/>哇喔!!\n<SURNAME/>气氛真热闹啊。\n<SURNAME/>对高中校园祭来说挺正规的嘛?\n']},
    'script:206_8:diag1': {'meta_zh': '麻耶', 'zh_pages': ['\n<SURNAME/>怎么了，<c13/>?\n<SURNAME/>这面具有什么不对吗?\n']},
    'script:206_8:diag2': {'meta_zh': '荣吉', 'zh_pages': ['\n<SURNAME/>那个康夫在搞什么!?\n<SURNAME/>那骷髅，不就是\n<SURNAME/>跟 Joker 拿的那个一样吗!?\n']},
    'script:206_8:diag3': {'meta_zh': '康夫', 'zh_pages': ['\n<SURNAME/>咦?\n<SURNAME/>已、已经够了。\n<SURNAME/>停、停下…<pause:30/>给我停下!!\n']},
    'script:206_8:diag4': {'meta_zh': '丽莎', 'zh_pages': ['\n<SURNAME/>得赶快阻止!!\n<SURNAME/>再这样下去，这里的人\n<SURNAME/>全部都会变成影人!\n']},
    'script:206_8:diag5': {'meta_zh': '杏奈', 'zh_pages': ['\n<SURNAME/>…真蠢。\n']},
    'script:206_8:diag6': {'meta_zh': '雪乃', 'zh_pages': ['\n<SURNAME/>这不是杏奈吗!?\n<SURNAME/>这里很危险，快逃!\n']},
    'script:206_8:diag7': {'meta_zh': '杏奈', 'zh_pages': ['\n<SURNAME/>…我知道。\n']},
    'script:206_8:diag8': {'meta_zh': '荣吉', 'zh_pages': ['\n<SURNAME/>康夫!!\n<SURNAME/>你小子，搞什么!?\n<SURNAME/>把那骷髅给老子停下!\n']},
    'script:206_8:diag9': {'meta_zh': '荣吉', 'zh_pages': ['\n<SURNAME/>给我等等!!\n<SURNAME/>追上去，<c12/>!\n']},
    'script:206_8:diag10': {'meta_zh': '麻耶', 'zh_pages': ['\n<SURNAME/>Thanks，<c13/>!\n<SURNAME/>要是面具一直戴着，\n<SURNAME/>我也得变成这群孩子的同伴了!\n']},
    'script:206_8:diag11': {'meta_zh': '荣吉', 'zh_pages': ['\n<SURNAME/>把全校的人都变成影人…<pause:30/>\n<SURNAME/>康夫那家伙到底在想什么!?\n<SURNAME/>再胡来，老子可不饶他!!\n']},
    'script:206_8:diag12': {'meta_zh': '丽莎', 'zh_pages': ['\n<SURNAME/>虽然没看清楚…\n<SURNAME/>但像荣吉说的，会长拿的那东西，\n<SURNAME/>不是跟那时候同一个骷髅吗?\n']},
    'script:206_8:diag13': {'meta_zh': '雪乃', 'zh_pages': ['\n<SURNAME/>杏奈在这里干嘛?\n<SURNAME/>而且刚才那种感觉…<pause:30/>\n<SURNAME/>难道是…\n']},
    'script:206_8:diag14': {'meta_zh': '渣校学生', 'zh_pages': ['\n<SURNAME/>本来想在化妆舞会上，\n<SURNAME/>钓个可爱女友的…\n<SURNAME/>不过，怎样都无所谓了…\n']},
    'script:206_8:diag15': {'meta_zh': '渣校学生', 'zh_pages': ['\n<SURNAME/>啊…呜…\n']},
    'script:206_8:diag16': {'meta_zh': '渣校学生', 'zh_pages': ['\n<SURNAME/>记得刚才还有个一起跳舞的妹子…\n<SURNAME/>怎么不见了…\n<SURNAME/>是我看错了吗~?\n']},
    'script:206_8:diag17': {'meta_zh': '渣校学生', 'zh_pages': ['\n<SURNAME/>哈、哈，开、开心呐~\n<SURNAME/>不过，哈、哈，为、为什么我，\n<SURNAME/>这么…累呢?\n']},
    'script:206_8:diag18': {'meta_zh': '艾尔敏学生', 'zh_pages': ['\n<SURNAME/>刚才被超帅的渣校生搭讪了!\n<SURNAME/>可一回头他就不见了…<pause:30/>\n<SURNAME/>那是不是做梦啊!?\n']},
    'script:206_8:diag19': {'meta_zh': '艾尔敏学生', 'zh_pages': ['\n<SURNAME/>不知怎的，累死了…\n<SURNAME/>不过回家又麻烦…\n']},
    'script:206_8:diag20': {'meta_zh': '轻子坂学生', 'zh_pages': ['\n<SURNAME/>呐呐，\n<SURNAME/>你不觉得人突然变少了吗?\n<SURNAME/>难、难道!<SURNAME/>已经散场啦?\n']},
    'script:206_8:diag21': {'meta_zh': '轻子坂学生', 'zh_pages': ['\n<SURNAME/>哦…啊…\n']},
    'script:206_8:diag22': {'meta_zh': '年轻女生', 'zh_pages': ['\n<SURNAME/>我明明很会跳舞的…\n<SURNAME/>浑身的力气都在流失…\n<SURNAME/>算了，无所谓…\n']},
    'script:206_8:diag23': {'meta_zh': '七姊妹学生', 'zh_pages': ['\n<SURNAME/>纹章诅咒也解开了…\n<SURNAME/>再找个渣校生当男友，万事 OK…\n<SURNAME/>…本来这么想，现在也无所谓了。\n']},
    'script:206_8:diag24': {'meta_zh': '七姊妹学生', 'zh_pages': ['\n<SURNAME/>…哈…呜…\n']},

    # ===== 207_8 =====
    'script:207_8:diag0': {'meta_zh': '荣吉', 'zh_pages': ['\n<SURNAME/>康夫，老子绝不饶…<pause:30/>\n<SURNAME/>咦?\n']},
    'script:207_8:diag1': {'meta_zh': '康夫的声音', 'zh_pages': ['\n<SURNAME/>呼嘻…\n<SURNAME/>你们来了啊。\n']},
    'script:207_8:diag2': {'meta_zh': '荣吉', 'zh_pages': ['\n<SURNAME/>你小子…<pause:30/>\n<SURNAME/>把大家变成影人，到底想干嘛!?\n']},
    'script:207_8:diag3': {'meta_zh': '康夫的声音', 'zh_pages': ['\n<SURNAME/>别那么大声嘛。\n<SURNAME/>说起来我可是\n<SURNAME/>重建这所学校的功臣呢。']},
    'script:207_8:diag4': {'meta_zh': '荣吉', 'zh_pages': ['\n<SURNAME/>功臣?']},
    'script:207_8:diag5': {'meta_zh': '康夫', 'zh_pages': ['\n<SURNAME/>春日山高中以前可是\n<SURNAME/>学力、风纪都垫底的烂校。\n<SURNAME/>现在呢?\n']},
    'script:207_8:diag6': {'meta_zh': '康夫', 'zh_pages': ['\n<SURNAME/>本校名声直线上升!\n<SURNAME/>当年被叫"渣"的学生们，\n<SURNAME/>如今成了女高中生的偶像!\n']},
    'script:207_8:diag7': {'meta_zh': '康夫', 'zh_pages': ['\n<SURNAME/>把学校重建到这种地步的，\n<SURNAME/>全靠身为学生会长的，\n<SURNAME/>我啊!!\n']},
    'script:207_8:diag8': {'meta_zh': '康夫', 'zh_pages': ['\n<SURNAME/>哎、哎呀，被识破啦…\n<SURNAME/>到底是从那防空洞，\n<SURNAME/>逃出来的人呢。\n']},
    'script:207_8:diag9': {'meta_zh': '丽莎', 'zh_pages': ['\n<SURNAME/>你是不是傻啊?\n']},
    'script:207_8:diag10': {'meta_zh': '康夫', 'zh_pages': ['\n<SURNAME/>别、别叫我傻啊!!\n<SURNAME/>你们这帮人，\n<SURNAME/>怎么会懂我的价值!\n']},
    'script:207_8:diag11': {'meta_zh': '康夫', 'zh_pages': ['\n<SURNAME/>哼、哼…<pause:30/>不管你们说什么，\n<SURNAME/>只要让校园祭办成功，\n<SURNAME/>我的名声就会更上层楼，这是事实。\n']},
    'script:207_8:diag12': {'meta_zh': '康夫', 'zh_pages': ['\n<SURNAME/>所以呢，三科君，我有事跟你商量。']},
    'script:207_8:diag13': {'meta_zh': '康夫', 'zh_pages': ['\n<SURNAME/>我打算就这样继续重建学校，\n<SURNAME/>不久的将来，\n<SURNAME/>把校内权力完全握在手中。\n']},
    'script:207_8:diag14': {'meta_zh': '康夫', 'zh_pages': ['\n<SURNAME/>所以希望你来\n<SURNAME/>掌管学校的"地下"那一面。\n']},
    'script:207_8:diag15': {'meta_zh': '康夫', 'zh_pages': ['\n<SURNAME/>咱俩联手，\n<SURNAME/>把学校的明面和暗面权力都拿到手，\n<SURNAME/>这里就会变成超棒的学校!\n']},
    'script:207_8:diag16': {'meta_zh': '康夫', 'zh_pages': ['\n<SURNAME/>怎么样?\n<SURNAME/>是不是完美的计划?\n']},
    'script:207_8:diag17': {'meta_zh': '荣吉', 'zh_pages': ['\n<SURNAME/>放你妈的屁!!\n<SURNAME/>那么龌龊的计划，谁会跟你干!\n']},
    'script:207_8:diag18': {'meta_zh': '荣吉', 'zh_pages': ['\n<SURNAME/>有空说这些废话，\n<SURNAME/>赶紧把大家变回来!!\n']},
    'script:207_8:diag19': {'meta_zh': '康夫', 'zh_pages': ['\n<SURNAME/>真是讲不通的人啊…\n']},
    'script:207_8:diag20': {'meta_zh': '康夫', 'zh_pages': ['\n<SURNAME/>而、而且，威胁我也没用哦。\n<SURNAME/>把大家变回来的方法，\n<SURNAME/>我从一开始就不知道。\n']},
    'script:207_8:diag21': {'meta_zh': '麻耶', 'zh_pages': ['\n<SURNAME/>只要把骷髅交给我们就行。\n<SURNAME/>我们来想办法。\n']},
    'script:207_8:diag22': {'meta_zh': '康夫', 'zh_pages': ['\n<SURNAME/>不、不、不行!\n<SURNAME/>这么做的话，\n<SURNAME/>我会被蕾蒂大人杀掉的!\n']},
    'script:207_8:diag23': {'meta_zh': '荣吉', 'zh_pages': ['\n<SURNAME/>你死活不交的话，\n<SURNAME/>那就动手抢过来!!\n']},
    'script:207_8:diag24': {'meta_zh': '康夫', 'zh_pages': ['\n<SURNAME/>暴力我不喜欢…<pause:30/>不过没办法。\n<SURNAME/>就为妨碍我的事，后悔着去死吧!\n<SURNAME/>呼、呼嘻、呼嘻嘻嘻嘻嘻嘻!!\n']},

    # ===== 210_8 =====
    'script:210_8:diag0': {'meta_zh': '导演', 'zh_pages': ['\n<SURNAME/>那么，正式开拍准备!<pause:30/>\n<SURNAME/>Sta~rt!\n']},
    'script:210_8:diag1': {'meta_zh': '未步', 'zh_pages': ['\n<SURNAME/>丽莎你呀，这阵子跑哪去啦?\n<SURNAME/>未步她们一直在找你呢!\n']},
    'script:210_8:diag2': {'meta_zh': '荻岛<SURNAME/>未步(おぎしま<SURNAME/>みほ)\n<SURNAME/>七姊妹学园 2-C 学生。绰号"未步"。\n<SURNAME/>丽莎的朋友，总跟麻美三人结伴行动。\n<SURNAME/>三人组中，性格最活泼跳脱。', 'zh_pages': []},
    'script:210_8:diag3': {'meta_zh': '未步', 'zh_pages': ['\n<SURNAME/>丽莎你呀，这阵子跑哪去啦?\n<SURNAME/>未步她们一直在找你呢!\n']},
    'script:210_8:diag4': {'meta_zh': '丽莎', 'zh_pages': ['\n<SURNAME/>说要出道，原来是真的呀。\n<SURNAME/>那么，传闻里那第三个人就是…\n']},
    'script:210_8:diag5': {'meta_zh': '麻美', 'zh_pages': ['\n<SURNAME/>丽莎，还记得在这拍的大头贴吗?\n<SURNAME/>"愿三个人都成为偶像~"\n<SURNAME/>就贴在这块板上嘛。\n']},
    'script:210_8:diag6': {'meta_zh': '柴田<SURNAME/>麻美(しばた<SURNAME/>まみ)\n<SURNAME/>七姊妹学园 2-C 学生。绰号"小麻"。\n<SURNAME/>丽莎的朋友，总跟未步三人结伴行动。\n<SURNAME/>三人组中，性格最沉稳。', 'zh_pages': []},
    'script:210_8:diag7': {'meta_zh': '麻美', 'zh_pages': ['\n<SURNAME/>那个心愿成真啦!!\n<SURNAME/>看了大头贴的佐佐木制作人，\n<SURNAME/>把我们三个一起签下啦!\n']},
    'script:210_8:diag8': {'meta_zh': '麻美', 'zh_pages': ['\n<SURNAME/>丽莎，还记得在这拍的大头贴吗?\n<SURNAME/>"愿三个人都成为偶像~"\n<SURNAME/>就贴在这块板上嘛。\n']},
    'script:210_8:diag9': {'meta_zh': '麻美', 'zh_pages': ['\n<SURNAME/>那个心愿成真啦!!\n<SURNAME/>看了大头贴的佐佐木制作人，\n<SURNAME/>把我们三个一起签下啦!\n']},
    'script:210_8:diag10': {'meta_zh': '丽莎', 'zh_pages': ['\n<SURNAME/>等、等等!\n<SURNAME/>大头贴是贴了，\n<SURNAME/>可我，当艺人之类的…\n']},
    'script:210_8:diag11': {'meta_zh': '未步', 'zh_pages': ['\n<SURNAME/>出道曲也超棒哦!!\n<SURNAME/>为双语的丽莎，\n<SURNAME/>专门加了英语 solo 段呢!\n']},
    'script:210_8:diag12': {'meta_zh': '麻美', 'zh_pages': ['\n<SURNAME/>丽莎?\n<SURNAME/>怎么了?\n']},
    'script:210_8:diag13': {'meta_zh': '丽莎', 'zh_pages': ['\n<SURNAME/>够了!!\n<SURNAME/>我才不想当什么艺人!\n']},
    'script:210_8:diag14': {'meta_zh': '丽莎', 'zh_pages': ['\n<SURNAME/>反正你俩两个人没自信红，\n<SURNAME/>才来拉我的吧!?\n<SURNAME/>别只在方便的时候装我朋友!!\n']},
    'script:210_8:diag15': {'meta_zh': '未步', 'zh_pages': ['\n<SURNAME/>怎么这样…<pause:30/>丽莎太过分了…\n<SURNAME/>未步她们的事，你讨厌了吗?\n']},
    'script:210_8:diag16': {'meta_zh': '麻美', 'zh_pages': ['\n<SURNAME/>…擅自做主，对不起。\n<SURNAME/>我们接下来要去 Giga·Macho\n<SURNAME/>录电台公开直播。\n']},
    'script:210_8:diag17': {'meta_zh': '麻美', 'zh_pages': ['\n<SURNAME/>改主意的话，丽莎也来好吗?\n<SURNAME/>未步，走吧…\n']},
    'script:210_8:diag18': {'meta_zh': '荣吉', 'zh_pages': ['\n<SURNAME/>话说到那份上，是不是过头了点?\n<SURNAME/>就这样让她俩走，没问题吗?\n']},
    'script:210_8:diag19': {'meta_zh': '丽莎', 'zh_pages': ['\n<SURNAME/>烦死了!!\n<SURNAME/>那俩自作主张的事。\n<SURNAME/>不管她们也罢!!\n']},
    'script:210_8:diag20': {'meta_zh': '麻耶', 'zh_pages': ['\n<SURNAME/>丽莎，稍微冷静点!\n<SURNAME/>话说回来，凭一张大头贴就让人出道，\n<SURNAME/>跟假面党有关的可能性更大了。\n']},
    'script:210_8:diag21': {'meta_zh': '雪乃', 'zh_pages': ['\n<SURNAME/>说不定能从那俩身上，\n<SURNAME/>问出更详细的情报。\n<SURNAME/>咱们也去 Giga·Macho 吧。\n']},

    # ===== 211_8 =====
    'script:211_8:diag0': {'meta_zh': '流星老兄', 'zh_pages': ['\n<SURNAME/>…这个单元到这里!\n<SURNAME/>等大家的来信哦!\n']},
    'script:211_8:diag1': {'meta_zh': '流星老兄', 'zh_pages': ['\n<SURNAME/>话说银次先生，今天节目里\n<SURNAME/>说要有重大发表，\n<SURNAME/>该不会就是…<pause:30/>\n']},
    'script:211_8:diag2': {'meta_zh': '银次', 'zh_pages': ['\n<SURNAME/>呵呵呵…<pause:30/>真服了你。\n<SURNAME/>那么，好吧。\n<SURNAME/>嘉宾刚好也到齐了。\n']},
    'script:211_8:diag3': {'meta_zh': '佐佐木<SURNAME/>银次(ささき<SURNAME/>ぎんじ)\n<SURNAME/>最近爆红的，做作的音乐制作人。\n<SURNAME/>如今名声响亮，\n<SURNAME/>原本只是几年前红过一首歌的过气艺人。', 'zh_pages': []},
    'script:211_8:diag4': {'meta_zh': '银次', 'zh_pages': ['\n<SURNAME/>回应大家的期待，\n<SURNAME/>现在就来公布 MUSES 的第三人。<pause:30/>\n<SURNAME/>丽莎·西尔弗曼!<SURNAME/>就是你!!\n']},
    'script:211_8:diag5': {'meta_zh': '丽莎', 'zh_pages': ['\n<SURNAME/>啊~~讨厌!\n<SURNAME/><c13/>，怎么办?\n<SURNAME/>救命呀!(カゥメンア)救我~!\n']},
    'script:211_8:diag6': {'meta_zh': '麻耶', 'zh_pages': ['\n<SURNAME/>哎呀!<SURNAME/>事到如今下定决心\n<SURNAME/>大大方方上吧!\n<SURNAME/>尽量套出更多情报来哦!\n']},
    'script:211_8:diag7': {'meta_zh': '麻美<SURNAME/>未步', 'zh_pages': ['\n<SURNAME/>电台前的各位!\n<SURNAME/>MUSES 三人到齐啦!!\n']},
    'script:211_8:diag8': {'meta_zh': '流星老兄', 'zh_pages': ['\n<SURNAME/>哎呀!!\n<SURNAME/>这位本人也被吓到的闪电发表!\n<SURNAME/>不愧是佐佐木<SURNAME/>银次，演出真带劲!\n']},
    'script:211_8:diag9': {'meta_zh': '麻耶', 'zh_pages': ['\n<SURNAME/>呐，<c13/>。<pause:30/>\n<SURNAME/>你不觉得，那个佐佐木身上\n<SURNAME/>有微弱的 Persona 共鸣吗?\n']},
    'script:211_8:diag10': {'meta_zh': '麻耶', 'zh_pages': ['\n<SURNAME/>那家伙也是假面党的人吗?\n<SURNAME/>如果是，丽莎就危险了。\n']},
    'script:211_8:diag11': {'meta_zh': '麻耶', 'zh_pages': ['\n<SURNAME/>不过，将计就计的话，\n<SURNAME/>说不定能拿到假面党的情报…<pause:30/>\n<SURNAME/>总之，就看丽莎能撑住多少了。\n']},
    'script:211_8:diag12': {'meta_zh': '流星老兄', 'zh_pages': ['\n<SURNAME/>那么，问个男听众最关心的\n<SURNAME/>问题吧!\n<SURNAME/>丽莎酱，有男朋友吗!?\n']},
    'script:211_8:diag13': {'meta_zh': '丽莎', 'zh_pages': ['\n<SURNAME/>唔係!(ンハイ)\n<SURNAME/>人家，有在交往的人哦!\n<SURNAME/>而且，今天就在现场!\n']},
    'script:211_8:diag14': {'meta_zh': '流星老兄', 'zh_pages': ['\n<SURNAME/>哎呀这可不得了!\n<SURNAME/>这次是丽莎酱的炸弹发言!\n<SURNAME/>那位男朋友，究竟是哪一位呢!?\n']},
    'script:211_8:diag15': {'meta_zh': '丽莎', 'zh_pages': ['\n<SURNAME/>站在那边的…\n<SURNAME/>个子高高，超帅的那位!\n<SURNAME/>呀，说出来啦~♥\n']},
    'script:211_8:diag16': {'meta_zh': '荣吉', 'zh_pages': ['\n<SURNAME/>…我?\n']},
    'script:211_8:diag17': {'meta_zh': '荣吉', 'zh_pages': ['\n<SURNAME/>是的话早说嘛…<pause:30/>\n<SURNAME/>Okay，Baby!!\n<SURNAME/>来，扑进本大爷怀里来吧♥\n']},
    'script:211_8:diag18': {'meta_zh': '丽莎', 'zh_pages': ['\n<SURNAME/>为什么…<pause:30/>\n<SURNAME/>偏偏是你呀!?\n']},
    'script:211_8:diag19': {'meta_zh': '流星老兄', 'zh_pages': ['\n<SURNAME/>好啦好啦，丽莎酱冷静点，啊?\n<SURNAME/>这毕竟是直播啊…\n']},
    'script:211_8:diag20': {'meta_zh': '丽莎', 'zh_pages': ['\n<SURNAME/>人家的情人(チンヤン)，\n<SURNAME/>才不是那种变态自恋男!\n']},
    'script:211_8:diag21': {'meta_zh': '流星老兄', 'zh_pages': ['\n<SURNAME/>呃，呃，那么银次先生!\n<SURNAME/>让人在意的 MUSES 出道曲嘛…\n']},
    'script:211_8:diag22': {'meta_zh': '银次', 'zh_pages': ['\n<SURNAME/>是首取材于最近\n<SURNAME/>年轻人间流传的"Joker 大人"游戏的曲子。\n<SURNAME/>歌名，直接就叫"JOKER"!\n']},
    'script:211_8:diag23': {'meta_zh': '麻耶', 'zh_pages': ['\n<SURNAME/>果然!\n']},
    'script:211_8:diag24': {'meta_zh': '银次', 'zh_pages': ['\n<SURNAME/>如你所见，\n<SURNAME/>为擅长英语的丽莎君\n<SURNAME/>专门准备了正式的英语 solo 段。\n']},
    'script:211_8:diag25': {'meta_zh': '流星老兄', 'zh_pages': ['\n<SURNAME/>原来如此，那么丽莎酱。\n<SURNAME/>用你的拿手英语，给听众朋友们\n<SURNAME/>说几句话好吗?\n']},
    'script:211_8:diag26': {'meta_zh': '流星老兄', 'zh_pages': ['\n<SURNAME/>本来想这么做的，可惜!\n<SURNAME/>告别时间到了。\n<SURNAME/>那么丽莎酱，我们都期待哦~!\n']},
    'script:211_8:diag27': {'meta_zh': '丽莎', 'zh_pages': ['\n<SURNAME/>O、O~K!\n<SURNAME/>Y、Yes!\n']},
    'script:211_8:diag28': {'meta_zh': '流星老兄', 'zh_pages': ['\n<SURNAME/>之后 MUSES 的活动安排，\n<SURNAME/>今天将出演青华区野外音乐堂\n<SURNAME/>举办的小型 live!\n']},
    'script:211_8:diag29': {'meta_zh': '流星老兄', 'zh_pages': ['\n<SURNAME/>"流星老兄的 SOUND·MAX"\n<SURNAME/>那么，下周再会!\n']},
    'script:211_8:diag30': {'meta_zh': '麻耶', 'zh_pages': ['\n<SURNAME/>佐佐木跟 MUSES 去的，\n<SURNAME/>是青华区的野外音乐堂。\n<SURNAME/>我们也去，<c13/>!\n']},

    # ===== 212_8 =====
    'script:212_8:diag0': {'meta_zh': '麻耶', 'zh_pages': ['\n<SURNAME/>这里就是后门吧。\n<SURNAME/>那么，怎么混进去呢?\n']},
    'script:212_8:diag1': {'meta_zh': '麻耶', 'zh_pages': ['\n<SURNAME/>就算骗说是来采访，\n<SURNAME/>没预约一下就穿帮了…\n']},
    'script:212_8:diag2': {'meta_zh': '荣吉', 'zh_pages': ['\n<SURNAME/>嘿<SURNAME/>Everybody!\n<SURNAME/>那边有几个像是打工的家伙呢。\n<SURNAME/>是不是在偷懒?\n']},
    'script:212_8:diag3': {'meta_zh': '雪乃', 'zh_pages': ['\n<SURNAME/>看着像。\n<SURNAME/>既然是打工的，\n<SURNAME/>身上应该带工作证吧?\n']},
    'script:212_8:diag4': {'meta_zh': '雪乃', 'zh_pages': ['\n<SURNAME/>不如把那个买过来?\n<SURNAME/>就说没抢到票之类的。\n']},
    'script:212_8:diag5': {'meta_zh': '雪乃', 'zh_pages': ['\n<SURNAME/>就算被压点价，\n<SURNAME/>能用钱解决的话，\n<SURNAME/>总比闹事强。\n']},
    'script:212_8:diag6': {'meta_zh': '麻耶', 'zh_pages': ['\n<SURNAME/>是啊。\n<SURNAME/>那就按小雪的方案来吧。\n<SURNAME/><c13/>，拜托你了。\n']},
    'script:212_8:diag7': {'meta_zh': '麻耶', 'zh_pages': ['\n<SURNAME/>我们在这等着，\n<SURNAME/><c13/>，去交涉一下好吗?\n<SURNAME/>就拜托你了。\n']},
    'script:212_8:diag8': {'meta_zh': '麻耶', 'zh_pages': ['\n<SURNAME/>怎么样，准备好了吗?\n<SURNAME/>一旦进去，\n<SURNAME/>没救出丽莎前应该出不来了。\n']},
    'script:212_8:diag9': {'meta_zh': '雪乃', 'zh_pages': ['\n<SURNAME/>这种打工嘛，钱能拿演唱会能看，\n<SURNAME/>给人感觉很划算，\n<SURNAME/>其实并没那么爽。\n']},
    'script:212_8:diag10': {'meta_zh': '雪乃', 'zh_pages': ['\n<SURNAME/>不过刚才那几个真不像话!\n<SURNAME/>一点工作态度都没有。\n<SURNAME/>虽说是我提的主意…\n']},
    'script:212_8:diag11': {'meta_zh': '荣吉', 'zh_pages': ['\n<SURNAME/>本大爷迟早有一天，也会在这里\n<SURNAME/>让全日本的 Baby 们尖叫\n<SURNAME/>吧…嗯嗯~Gorgeous!\n']},
    'script:212_8:diag12': {'meta_zh': '荣吉', 'zh_pages': ['\n<SURNAME/>未来巨星，现在只是个打工狗么…<pause:30/>\n<SURNAME/>本来想堂堂正正登台的，\n<SURNAME/>不过基层历练也重要嘛…\n']},
    'script:212_8:diag13': {'meta_zh': '演唱会工作人员', 'zh_pages': ['\n<SURNAME/>啊~好累啊…<pause:30/>\n<SURNAME/>昨天在社团聚会上喝过头了…<pause:30/>\n<SURNAME/>谁来替我顶班啊。\n']},
    'script:212_8:diag14': {'meta_zh': '演唱会工作人员', 'zh_pages': ['\n<SURNAME/>我今天本来也要去看\n<SURNAME/>奥碧莉雅酱的 live 的，\n<SURNAME/>突然被叫来…\n']},
    'script:212_8:diag15': {'meta_zh': '演唱会工作人员', 'zh_pages': ['\n<SURNAME/>问过朋友，\n<SURNAME/>大家都忙，没人替我顶…\n']},
    'script:212_8:diag16': {'meta_zh': '演唱会工作人员', 'zh_pages': ['\n<SURNAME/>不行不行，这里闲杂人等止步。\n<SURNAME/>麻烦归麻烦，这也是工作嘛。\n']},
    'script:212_8:diag17': {'meta_zh': '演唱会工作人员', 'zh_pages': ['\n<SURNAME/>啥…?<SURNAME/>愿意帮我顶班?\n<SURNAME/>没买到票，无论如何都想看?\n<SURNAME/>还有同伴…突然这么说我也…\n']},
    'script:212_8:diag18': {'meta_zh': '演唱会工作人员', 'zh_pages': ['\n<SURNAME/>嗯，被发现要挨骂…\n<SURNAME/>不过又懒得干…\n']},
    'script:212_8:diag19': {'meta_zh': '演唱会工作人员', 'zh_pages': ['\n<SURNAME/>那、那好，加起来一万日元，\n<SURNAME/>就把我俩的工作证卖给你们。\n<SURNAME/>我们也担风险呢，不算贵吧?\n']},
    'script:212_8:diag20': {'meta_zh': '演唱会工作人员', 'zh_pages': ['\n<SURNAME/>哟，钱凑够了?\n<SURNAME/>一万日元，要买吗?\n']},
    'script:212_8:diag21': {'meta_zh': '<SURNAME/>一万日元，要买吗?\n<option:2/>买了\n还是算了\n<option_end/><c02/>', 'zh_pages': []},
    'script:212_8:diag22': {'meta_zh': '演唱会工作人员', 'zh_pages': ['\n<SURNAME/>好、好，多谢惠顾。\n<SURNAME/>那么这是我们的<c1d:9/>工作证<c1d:1/>。\n<SURNAME/>记得好歹要好好干哦，拜托啦!\n']},
    'script:212_8:diag23': {'meta_zh': '演唱会工作人员', 'zh_pages': ['\n<SURNAME/>啥，没带钱啊?\n<SURNAME/>那就没法卖咯。\n<SURNAME/>凑够钱再来吧。\n']},
    'script:212_8:diag24': {'meta_zh': '演唱会工作人员', 'zh_pages': ['\n<SURNAME/>啥，不要啦?\n<SURNAME/>真可惜啊。\n<SURNAME/>凑到钱了随时来哦。\n']},

    # ===== 213_8 =====
    'script:213_8:diag0': {'meta_zh': '麻耶', 'zh_pages': ['\n<SURNAME/>这些女孩，似乎也跟丽莎一样，\n<SURNAME/>因传闻的大头贴成了偶像呢。\n']},
    'script:213_8:diag1': {'meta_zh': '雪乃', 'zh_pages': ['\n<SURNAME/>SPADE…<pause:30/>\n<SURNAME/>名字听着有点山寨啊。\n<SURNAME/>真能红吗?\n']},
    'script:213_8:diag2': {'meta_zh': '荣吉', 'zh_pages': ['\n<SURNAME/>大姐，这么说就没意思啦。\n<SURNAME/>虽然她们看着挺蠢…\n<SURNAME/>这里出于礼节，至少要个签名…\n']},
    'script:213_8:diag3': {'meta_zh': '荣吉', 'zh_pages': ['\n<SURNAME/>Okay!<SURNAME/>Come on Babies!!\n<SURNAME/>未来巨星 artist 的签名要不要呀?\n<SURNAME/>将来可是会升值的哦~♥\n']},
    'script:213_8:diag4': {'meta_zh': '荣吉', 'zh_pages': ['\n<SURNAME/>那萝莉控家伙，就在隔壁屋哦!\n<SURNAME/>丽莎肯定也在!!\n']},
    'script:213_8:diag5': {'meta_zh': '经纪人', 'zh_pages': ['\n<SURNAME/>那个叫丽莎的小丫头也是，\n<SURNAME/>凭啥我得给这帮吵闹的小屁孩\n<SURNAME/>当经纪人呢…\n']},
    'script:213_8:diag6': {'meta_zh': '经纪人', 'zh_pages': ['\n<SURNAME/>那帮吵闹的小屁孩，\n<SURNAME/>不就在隔壁吗?\n<SURNAME/>被佐佐木先生叫去了。\n']},
    'script:213_8:diag7': {'meta_zh': '亚纪', 'zh_pages': ['\n<SURNAME/>那老太婆，真烦。\n<SURNAME/>给她一刀如何?\n']},
    'script:213_8:diag8': {'meta_zh': '彩', 'zh_pages': ['\n<SURNAME/>啊哈哈哈哈哈哈哈哈哈哈!!\n<SURNAME/>我是彩~!!\n<SURNAME/>啊哈哈哈哈哈哈哈哈哈哈!!\n']},
    'script:213_8:diag9': {'meta_zh': '拓美', 'zh_pages': ['\n<SURNAME/>我是拓美~\n<SURNAME/>不是男生哦~\n<SURNAME/>不输 MUSES，会加油的!!\n']},
    'script:213_8:diag10': {'meta_zh': '桂', 'zh_pages': ['\n<SURNAME/>我是桂~\n<SURNAME/>我们四人，就是 SPADE(黑桃)~\n<SURNAME/>到前天为止还是普通女高中生哦~\n']},
    'script:213_8:diag11': {'meta_zh': '纸箱', 'zh_pages': ['\n<SURNAME/><c1d:9/>装着 MUSES 的宣传册。<c1d:1/>\n']},
    'script:213_8:diag12': {'meta_zh': '纸箱', 'zh_pages': ['\n<SURNAME/><c1d:9/>装着 MUSES 的宣传册。<c1d:1/>\n']},
    'script:213_8:diag13': {'meta_zh': '纸箱', 'zh_pages': ['\n<SURNAME/><c1d:9/>装着 MUSES 的宣传册。<c1d:1/>\n']},
    'script:213_8:diag14': {'meta_zh': '储物柜', 'zh_pages': ['\n<SURNAME/><c1d:9/>上着锁。<c1d:1/>\n']},
    'script:213_8:diag15': {'meta_zh': '储物柜', 'zh_pages': ['\n<SURNAME/><c1d:9/>上着锁。<c1d:1/>\n']},
    'script:213_8:diag16': {'meta_zh': '储物柜', 'zh_pages': ['\n<SURNAME/><c1d:9/>上着锁。<c1d:1/>\n']},
    'script:213_8:diag17': {'meta_zh': '储物柜', 'zh_pages': ['\n<SURNAME/><c1d:9/>上着锁。<c1d:1/>\n']},
    'script:213_8:diag18': {'meta_zh': '储物柜', 'zh_pages': ['\n<SURNAME/><c1d:9/>上着锁。<c1d:1/>\n']},

    # ===== 214_8 =====
    'script:214_8:diag0': {'meta_zh': '银次嗓音的男人', 'zh_pages': ['\n<SURNAME/>呵呵…我可爱的蝴蝶们…<pause:30/>\n<SURNAME/>从你们的梦中生出的能量，\n<SURNAME/>将引导假面党之梦…\n']},
    'script:214_8:diag1': {'meta_zh': '银次嗓音的男人', 'zh_pages': ['\n<SURNAME/>再扇动翅膀。\n<SURNAME/>飞得更高…更远…<pause:30/>\n<SURNAME/>免得梦消散尽…\n']},
    'script:214_8:diag2': {'meta_zh': '麻美<SURNAME/>未步', 'zh_pages': ['\n<SURNAME/>Yair·Camen…\n']},
    'script:214_8:diag3': {'meta_zh': '托勒斯公子', 'zh_pages': ['\n<SURNAME/>今天就由我佐佐木<SURNAME/>银次…<pause:30/>\n<SURNAME/>不，托勒斯公子来介绍，\n<SURNAME/>由我亲自捧出的新伙伴们。\n']},
    'script:214_8:diag4': {'meta_zh': '托勒斯公子', 'zh_pages': ['\n<SURNAME/>来吧，丽莎君…<pause:30/>\n<SURNAME/>呼唤 Joker 大人吧。\n']},
    'script:214_8:diag5': {'meta_zh': '麻美', 'zh_pages': ['\n<SURNAME/>丽莎…<pause:30/>\n<SURNAME/>一起飞吧?\n']},
    'script:214_8:diag6': {'meta_zh': '未步', 'zh_pages': ['\n<SURNAME/>未步她们，约定过的嘛。\n<SURNAME/>三个人都要当偶像。\n<SURNAME/>啊?\n']},
    'script:214_8:diag7': {'meta_zh': '丽莎', 'zh_pages': ['\n<SURNAME/>约定…\n']},
    'script:214_8:diag8': {'meta_zh': '丽莎', 'zh_pages': ['\n<SURNAME/>现在…您是哪位?\n']},
    'script:214_8:diag9': {'meta_zh': '丽莎', 'zh_pages': ['\n<SURNAME/>对不起…小麻、未步。\n<SURNAME/>你俩的心意，我超高兴…<pause:30/>\n<SURNAME/>可是，没法一起去呀…\n']},
    'script:214_8:diag10': {'meta_zh': '丽莎', 'zh_pages': ['\n<SURNAME/><c13/>他们也是重要朋友…不能背叛!<pause:30/>\n<SURNAME/>而且…靠别人施舍的梦，\n<SURNAME/>怎么可能得到幸福!!\n']},
    'script:214_8:diag11': {'meta_zh': '丽莎', 'zh_pages': ['\n<SURNAME/>麻耶姐他们就快来了!\n<SURNAME/>一起逃吧。\n<SURNAME/>不能待在这种地方!!\n']},
    'script:214_8:diag12': {'meta_zh': '托勒斯公子', 'zh_pages': ['\n<SURNAME/>哼…被摆了一道。<pause:30/>\n<SURNAME/>也罢。SPADE 诸位，上台。<pause:30/>\n<SURNAME/>曲目是"异国之咏"…"JOKER"。\n']},
    'script:214_8:diag13': {'meta_zh': '托勒斯公子', 'zh_pages': ['\n<SURNAME/>那么…<pause:30/>\n<SURNAME/>不飞的蝴蝶，就做成标本吧!\n']},
}
PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'all_translatable.json')
data = json.load(open(PATH, encoding='utf-8'))
applied = 0
for entry in data:
    eid = entry['id']
    if eid not in T: continue
    tr = T[eid]
    if 'meta_zh' in tr and tr['meta_zh']:
        entry['meta_zh'] = tr['meta_zh']
    for i, zh in enumerate(tr.get('zh_pages', [])):
        if i < len(entry['pages']):
            entry['pages'][i]['zh'] = zh
    applied += 1
with open(PATH, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
print(f'已应用 {applied} 条翻译')
